[package]
name = "foundation314"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
csv = "1.3.1"
pathbuf = "1.0.0"
walkdir = "2.5.0"

[lib]
name = "foundation314"
path = "src/lib.rs"

